#!/usr/bin/python3
""" This module defines base model needed for the AirBnB console"""

class BaseModel:
    """ 
    Class to create ......
    
    Methods:
        ......
        ......
        ......
    """
    pass